apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm-demo
          image: pwstaging/demo-crm:latest
          envFrom:
          - configMapRef:
              name: crm-configmap
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: crm-mongo-secret
                  key: MONGODB_URI
